# Generated by Django 5.2.4 on 2025-08-03 13:32

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, default=0)),
                ('code', models.CharField(db_index=True, default='UNKNOWN', max_length=50)),
                ('location', models.CharField(default='UNKNOWN', max_length=100)),
                ('status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=10)),
                ('temperature_min', models.FloatField(blank=True, null=True)),
                ('temperature_max', models.FloatField(blank=True, null=True)),
                ('humidity_min', models.FloatField(blank=True, null=True)),
                ('humidity_max', models.FloatField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_temp_min', models.FloatField(blank=True, null=True)),
                ('alert_temp_max', models.FloatField(blank=True, null=True)),
                ('alert_humidity_min', models.FloatField(blank=True, null=True)),
                ('alert_humidity_max', models.FloatField(blank=True, null=True)),
                ('logging_interval_minutes', models.PositiveIntegerField(default=15)),
                ('button_stop_enabled', models.BooleanField(default=True)),
                ('mute_button_enabled', models.BooleanField(default=True)),
                ('alarm_tone_enabled', models.BooleanField(default=True)),
                ('storage_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.manufacturer')),
            ],
            options={
                'verbose_name': 'historical device',
                'verbose_name_plural': 'historical devices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalManufacturer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical manufacturer',
                'verbose_name_plural': 'historical manufacturers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
