# Generated by Django 5.2.4 on 2025-09-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_historicaldevice_historicalmanufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmanufacturer',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDevice',
        ),
        migrations.DeleteModel(
            name='HistoricalManufacturer',
        ),
    ]
