# Generated by Django 5.2.4 on 2025-07-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_device_created_at_device_started_at_alarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarm_type',
            field=models.CharField(choices=[('TEMP_HI', 'Temperature Too High'), ('TEMP_LO', 'Temperature Too Low'), ('HUM_HI', 'Humidity Too High'), ('HUM_LO', 'Humidity Too Low'), ('DC', 'Device Disconnected')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='triggered_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
