# Generated by Django 5.2.4 on 2025-07-22 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_alarm_alarm_type_alter_alarm_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
