# Generated by Django 5.2.4 on 2025-09-17 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_historicalmanufacturer_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
