# Generated by Django 5.2.4 on 2025-07-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='website',
        ),
    ]
