# Generated by Django 5.2.4 on 2025-07-23 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_manufacturer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.manufacturer'),
        ),
    ]
