# Generated by Django 5.2.4 on 2025-07-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_device_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
