# Generated by Django 5.2.4 on 2025-07-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_remove_device_name_device_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarm_type',
            field=models.CharField(choices=[('TEMP_HI', 'Temperature Too High'), ('TEMP_LO', 'Temperature Too Low'), ('HUM_HI', 'Humidity Too High'), ('HUM_LO', 'Humidity Too Low'), ('DC', 'Device Disconnected'), ('SD', 'Stop button disabled'), ('MD', 'Mute Button disabled')], max_length=10),
        ),
    ]
